{
 "title": "Avail Node Dashboard",
 "description": "This dashboard provides a comprehensive view of key metrics from Avail node. It offers insights into node performance, health and activity.",
 "tags": [ "substrate" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(substrate_sub_libp2p_peers_count,instance)"
    }
   },
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(substrate_sub_libp2p_peers_count,chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <br>\n    <img src=\"https://services.kjnodes.com/assets/images/logos/avail.png\"><br><br>\n    <h1>Avail Node Dashboard</h1>\n    <h5>⚡️ Powered by <a href=\"https://kjnodes.com\">kjnodes</a></h5>\n</div>"
   }
  },
  { "title": "kjnodes Avail services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/mainnet/avail/\" target=\"_blank\">Avail Services</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/mainnet/avail/installation/\" target=\"_blank\">Node Installation</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/mainnet/avail/upgrade/\" target=\"_blank\">Node Upgrade</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/mainnet/avail/snapshot/\" target=\"_blank\">Snapshot</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/mainnet/avail/useful-commands/\" target=\"_blank\">Useful Commands</a></h1>\r\n</div>"
   }
  },
  { "title": "Avail Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "# Avail Node Metrics\n\n*Metrics collected from a Avail Prometheus endpoint.*\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>System</h2>\r\n</div>"
   }
  },
  {
   "title": "Build Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "substrate_build_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - substrate_process_start_time_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(substrate_block_height{status=\"sync_target\"}) - sum(substrate_block_height{status=\"best\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", instance=\"$instance\"}",
     "legendFormat": "best"
    },
    {
     "expr": "substrate_block_height{status=\"sync_target\", instance=\"$instance\"}",
     "legendFormat": "target"
    }
   ]
  },
  {
   "title": "Node type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "substrate_node_roles{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"sync_target\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Network</h2>\r\n</div>"
   }
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sync_peers{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(substrate_sub_libp2p_network_bytes_total{direction=\"in\", instance=\"$instance\"}[1m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum(rate(substrate_sub_libp2p_network_bytes_total{direction=\"out\", instance=\"$instance\"}[1m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Blockchain</h2>\r\n</div>"
   }
  },
  {
   "title": "Block time",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "600 / round(increase(substrate_block_height{status=\"sync_target\", instance=\"$instance\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(substrate_block_height{status=\"sync_target\", instance=\"$instance\"}[10m]))/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks sync per minute",
   "type": "timeseries",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round(increase(substrate_block_height{status=\"best\", instance=\"$instance\"}[1m]))",
     "legendFormat": "blocks per minute"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket{instance=\"$instance\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{instance=\"$instance\"}[1m]) - rate(substrate_tasks_polling_duration_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "substrate_database_cache_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages{instance=\"$instance\"}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{instance=\"$instance\"}",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_number_leaves{instance=\"$instance\"}"
    }
   ]
  }
 ]
}